// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class ActiveJwt
{
    public string Username { get; set; }

    public string Token { get; set; }

    public DateTime? ExpiryDate { get; set; }
}