// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class ProductCategoryType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BuyOrderDetail> BuyOrderDetails { get; set; } = new List<BuyOrderDetail>();

    public virtual ICollection<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();

    public virtual ICollection<PurchasePriceRatio> PurchasePriceRatios { get; set; } = new List<PurchasePriceRatio>();
}