// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class Account
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Status { get; set; }

    public virtual Role Role { get; set; }

    public virtual Staff Staff { get; set; }

    public Account()
    {
    }

    public Account(int id, int roleId, string username, string password, string status, Role role, Staff staff)
    {
        Id = id;
        RoleId = roleId;
        Username = username;
        Password = password;
        Status = status;
        Role = role;
        Staff = staff;
    }
}