// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class BuyOrderDetail
{
    public int Id { get; set; }
    
    public string ProductName { get; set; }
    
    public int Quantity { get; set; }
    
    [JsonIgnore]

    public int BuyOrderId { get; set; }
    [JsonIgnore]

    public int CategoryTypeId { get; set; }

    public string DiamondGradingCode { get; set; }
    [JsonIgnore]

    public int? MaterialId { get; set; }

    public decimal? MaterialWeight { get; set; }
    [JsonIgnore]

    public int? PurchasePriceRatioId { get; set; }

    public decimal UnitPrice { get; set; }

    [JsonIgnore]
    public virtual BuyOrder BuyOrder { get; set; }
    [JsonIgnore]

    public virtual ProductCategoryType CategoryType { get; set; }
    [JsonIgnore]

    public virtual Material Material { get; set; }
    [JsonIgnore]

    public virtual PurchasePriceRatio PurchasePriceRatio { get; set; }
}