// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class Carat
{
    public int Id { get; set; }

    public decimal Weight { get; set; }

    public string Description { get; set; }

    public virtual ICollection<DiamondPriceList> DiamondPriceLists { get; set; } = new List<DiamondPriceList>();

    public virtual ICollection<Diamond> Diamonds { get; set; } = new List<Diamond>();
}