// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace JSSATSProject.Repository.Entities;

public partial class Customer
{
    public int Id { get; set; }

    public int? PointId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Point Point { get; set; }

    public Customer()
    {

    }

    public Customer(int id, int? poinId, string firstname, string lastname, string phone, string email, string gender, string address)
    {
        Id = id;
        PointId = poinId;
        Firstname = firstname;
        Lastname = lastname;
        Phone = phone;
        Email = email;
        Gender = gender;
        Address = address;
    }

    public Customer(int id, int? pointId, string firstname, string lastname, string phone, string email, string gender, string address, List<Order> orders, List<Payment> payments, Point point)
    {
        Id = id;
        PointId = pointId;
        Firstname = firstname;
        Lastname = lastname;
        Phone = phone;
        Email = email;
        Gender = gender;
        Address = address;
        Orders = orders;
        Payments = payments;
        Point = point;
    }
}


