// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class DiamondPriceList
{
    public int Id { get; set; }

    public int ColorId { get; set; }

    public int CutId { get; set; }

    public int OriginId { get; set; }

    public int ClarityId { get; set; }

    public int CaratId { get; set; }

    public decimal Price { get; set; }

    public DateTime EffectiveDate { get; set; }

    public virtual Carat Carat { get; set; }

    public virtual Clarity Clarity { get; set; }

    public virtual Color Color { get; set; }

    public virtual Cut Cut { get; set; }

    public virtual Origin Origin { get; set; }
}