// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class Guarantee
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Description { get; set; }

    public DateTime EffectiveDate { get; set; }

    public DateTime ExpiredDate { get; set; }

    public virtual Product Product { get; set; }

    public Guarantee()
    {
        
    }

    public Guarantee(int id, int productId, string description, DateTime effectiveDate, DateTime expiredDate, Product product)
    {
        Id = id;
        ProductId = productId;
        Description = description;
        EffectiveDate = effectiveDate;
        ExpiredDate = expiredDate;
        Product = product;
    }
}