// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class GuaranteePolicy
{
    public int Id { get; set; }

    public int? ProductCategoryId { get; set; }

    public int Duration { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }
}