// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class MaterialPriceList
{
    public int Id { get; set; }

    public int MaterialId { get; set; }

    public decimal BuyPrice { get; set; }

    public decimal SellPrice { get; set; }

    public DateTime EffectiveDate { get; set; }

    public virtual Material Material { get; set; }
}