// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class MaterialPriceList
{
    public int Id { get; set; }

    public int MaterialId { get; set; }

    public decimal BuyPrice { get; set; }

    public decimal SellPrice { get; set; }

    public DateTime EffectiveDate { get; set; }
[JsonIgnore]
    public virtual Material Material { get; set; }

    public MaterialPriceList()
    {
        
    }

    public MaterialPriceList(int id, int materialId, decimal buyPrice, decimal sellPrice, DateTime effectiveDate, Material material)
    {
        Id = id;
        MaterialId = materialId;
        BuyPrice = buyPrice;
        SellPrice = sellPrice;
        EffectiveDate = effectiveDate;
        Material = material;
    }
}