// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public string Size { get; set; }

    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

    public decimal SizePrice { get; set; }

    public string Status { get; set; }

    public int? PromotionId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual Promotion Promotion { get; set; }
}