//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class ProductDiamond
{
    public int ProductId { get; set; }
   
    public int DiamondId { get; set; }

    [JsonIgnore]
    public virtual Product Product { get; set; }

    public virtual Diamond Diamond { get; set; }

}