// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class ProductMaterial
{
    public int MaterialId { get; set; }

    public int ProductId { get; set; }

    public decimal? Weight { get; set; }

    public virtual Material Material { get; set; }

    public virtual Product Product { get; set; }
}