// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class ProductCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TypeId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ProductCategoryType Type { get; set; }
    [JsonIgnore]
    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
    [JsonIgnore]
    public virtual ICollection<PromotionRequest> Requests { get; set; } = new List<PromotionRequest>();
}