//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace JSSATSProject.Repository.E01;

//public partial class ProductDiamond
//{
//    public int ProductId { get; set; }

//    public int DiamondId { get; set; }
//}