// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class ProductCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TypeId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ProductCategoryType Type { get; set; }

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();

    public ProductCategory()
    {
        
    }
    public ProductCategory(int id, string name, int typeId, string status, ICollection<Product> products, ProductCategoryType type, ICollection<Promotion> promotions)
    {
        Id = id;
        Name = name;
        TypeId = typeId;
        Status = status;
        Products = products;
        Type = type;
        Promotions = promotions;
    }
}