// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class PurchasePriceRatio
{
    public int Id { get; set; }

    public int CategoryTypeId { get; set; }

    public string Type { get; set; }

    public decimal Percentage { get; set; }

    public virtual ICollection<BuyOrderDetail> BuyOrderDetails { get; set; } = new List<BuyOrderDetail>();

    public virtual ProductCategoryType CategoryType { get; set; }
}