// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class ReturnBuyBackPolicy
{
    public int Id { get; set; }

    public string Description { get; set; }

    public DateTime EffectiveDate { get; set; }

    public string Status { get; set; }

    public ReturnBuyBackPolicy()
    {
        
    }
    public ReturnBuyBackPolicy(int id, string description, DateTime effectiveDate, string status)
    {
        Id = id;
        Description = description;
        EffectiveDate = effectiveDate;
        Status = status;
    }
}