// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class SellOrderDetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

    public string Status { get; set; }

    public int? PromotionId { get; set; }
    public virtual ICollection<Guarantee> Guarantees { get; set; } = new List<Guarantee>();

    [JsonIgnore]
    public virtual SellOrder Order { get; set; }

    public virtual Product Product { get; set; }
    [JsonIgnore]
    public virtual Promotion Promotion { get; set; }
    
    public virtual ICollection<Guarantee> Guarantees { get; set; } = new List<Guarantee>();

}