// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class SpecialDiscountRequest
{
    public int RequestId { get; set; }

    public int CustomerId { get; set; }

    public int StaffId { get; set; }

    public decimal DiscountRate { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? ApprovedBy { get; set; }

    public virtual Staff ApprovedByNavigation { get; set; }

    public virtual Customer Customer { get; set; }
    [JsonIgnore]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Staff Staff { get; set; }
}