// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class Staff
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }
    [JsonIgnore]
    public virtual ICollection<BuyOrder> BuyOrders { get; set; } = new List<BuyOrder>();
    [JsonIgnore]
    public virtual ICollection<PromotionRequest> PromotionRequestApprovedByNavigations { get; set; } = new List<PromotionRequest>();
    [JsonIgnore]
    public virtual ICollection<PromotionRequest> PromotionRequestManagers { get; set; } = new List<PromotionRequest>();
    [JsonIgnore]
    public virtual ICollection<SellOrder> SellOrders { get; set; } = new List<SellOrder>();
    [JsonIgnore]
    public virtual ICollection<SpecialDiscountRequest> SpecialDiscountRequestApprovedByNavigations { get; set; } = new List<SpecialDiscountRequest>();
    [JsonIgnore]
    public virtual ICollection<SpecialDiscountRequest> SpecialDiscountRequestStaffs { get; set; } = new List<SpecialDiscountRequest>();
}