// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class Staff
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Gender { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
    public Staff()
    {
        
    }

    public Staff(int id, int accountId, string firstname, string lastname, string phone, string email, string address, string gender, string status, Account account, ICollection<Order> orders)
    {
        Id = id;
        AccountId = accountId;
        Firstname = firstname;
        Lastname = lastname;
        Phone = phone;
        Email = email;
        Address = address;
        Gender = gender;
        Status = status;
        Account = account;
        Orders =  orders;
    }
}