// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JSSATSProject.Repository.Entities;

public partial class Stall
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TypeId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual StallType Type { get; set; }
}