// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JSSATSProject.Repository.Entities;

public partial class StallType
{
    [JsonIgnore]
    public int Id { get; set; }

    public string Name { get; set; }
    [JsonIgnore]

    public string Status { get; set; }
    [JsonIgnore]

    public virtual ICollection<Stall> Stalls { get; set; } = new List<Stall>();
}